<ul>
<div class="news_position"> <div id="news_text"><a href="/agro-articles/1-Vyraschivanie-tomatov.htm"><img width="210" border="0" src="/agro-articles/pictures/1t.jpg"></a> <b><a href="/agro-articles/1-Vyraschivanie-tomatov.htm">Выращивание томатов</a></b></div> <div class="news_line"></div></div>
<div class="news_position"> <div id="news_text"><a href="/agro-articles/2-Vyraschivanie-pertsa.htm"><img width="210" border="0" src="/agro-articles/pictures/2t.jpg"></a> <b><a href="/agro-articles/2-Vyraschivanie-pertsa.htm">Выращивание перца</a></b></div> <div class="news_line"></div></div>
<div class="news_position"> <div id="news_text"><a href="/agro-articles/3-Vyraschivanie-ogurtsov.htm"><img width="210" border="0" src="/agro-articles/pictures/3t.jpg"></a> <b><a href="/agro-articles/3-Vyraschivanie-ogurtsov.htm">Выращивание огурцов</a></b></div> <div class="news_line"></div></div>
<div class="news_position"> <div id="news_text"><a href="/agro-articles/4-Vyraschivanie-kapusty.htm"><img width="210" border="0" src="/agro-articles/pictures/4t.jpg"></a> <b><a href="/agro-articles/4-Vyraschivanie-kapusty.htm">Выращивание капусты</a></b></div> <div class="news_line"></div></div>
<div class="news_position"> <div id="news_text"><a href="/agro-articles/5-Vyraschivanie-repy.htm"><img width="210" border="0" src="/agro-articles/pictures/5t.jpg"></a> <b><a href="/agro-articles/5-Vyraschivanie-repy.htm">Выращивание репы</a></b></div>  <div class="news_line"></div></div>
<div class="news_position"> <div id="news_text"><a href="/agro-articles/6-Vyraschivanie-redky.htm"><img width="210" border="0" src="/agro-articles/pictures/6t.jpg"></a> <b><a href="/agro-articles/6-Vyraschivanie-redky.htm">Выращивание редьки</a></b></div>  <div class="news_line"></div></div>
<div class="news_position"> <div id="news_text"><a href="/agro-articles/7-Vyraschivanie-redisa.htm"><img width="210" border="0" src="/agro-articles/pictures/7t.jpg"></a> <b><a href="/agro-articles/7-Vyraschivanie-redisa.htm">Выращивание редиса</a></b></div>  <div class="news_line"></div></div>
<div class="news_position"> <div id="news_text"><a href="/agro-articles/8-Vyraschivanie-tykvy.htm"><img width="210" border="0" src="/agro-articles/pictures/8t.jpg"></a> <b><a href="/agro-articles/8-Vyraschivanie-tykvy.htm">Выращивание тыквы</a></b></div>  <div class="news_line"></div></div>
<div class="news_position"> <div id="news_text"><a href="/agro-articles/9-Vyraschivanie-kabachkov.htm"><img width="210" border="0" src="/agro-articles/pictures/9t.jpg"></a> <b><a href="/agro-articles/9-Vyraschivanie-kabachkov.htm">Выращивание кабачков</a></b></div>  <div class="news_line"></div></div>
<div class="news_position"> <div id="news_text"><a href="/agro-articles/10-Vyraschivanie-patissonov.htm"><img width="210" border="0" src="/agro-articles/pictures/10t.jpg"></a> <b><a href="/agro-articles/10-Vyraschivanie-patissonov.htm">Выращивание патиссонов</a></b></div>  <div class="news_line"></div></div>
<div class="news_position"> <div id="news_text"><a href="/agro-articles/11-Vyraschivanie-morkovy.htm"><img width="210" border="0" src="/agro-articles/pictures/11t.jpg"></a> <b><a href="/agro-articles/11-Vyraschivanie-morkovy.htm">Выращивание моркови</a></b></div>  <div class="news_line"></div></div>
<div class="news_position"> <div id="news_text"><a href="/agro-articles/12-Vyraschivanie-chesnoka.htm"><img width="210" border="0" src="/agro-articles/pictures/12t.jpg"></a> <b><a href="/agro-articles/12-Vyraschivanie-chesnoka.htm">Выращивание чеснока</a></b></div>  <div class="news_line"></div></div>
<div class="news_position"> <div id="news_text"><a href="/agro-articles/13-Vyraschivanie-luka.htm"><img width="210" border="0" src="/agro-articles/pictures/13t.jpg"></a> <b><a href="/agro-articles/13-Vyraschivanie-luka.htm">Выращивание лука</a></b></div>  <div class="news_line"></div></div>
<div class="news_position"> <div id="news_text"><a href="/agro-articles/14-Vyraschivanie-svekly.htm"><img width="210" border="0" src="/agro-articles/pictures/14t.jpg"></a> <b><a href="/agro-articles/14-Vyraschivanie-svekly.htm">Выращивание свеклы</a></b></div>  <div class="news_line"></div></div>
<div class="news_position"> <div id="news_text"><a href="/agro-articles/15-Vyraschivanie-goroha.htm"><img width="210" border="0" src="/agro-articles/pictures/15t.jpg"></a> <b><a href="/agro-articles/15-Vyraschivanie-goroha.htm">Выращивание гороха</a></b></div>  <div class="news_line"></div></div>
<div class="news_position"> <div id="news_text"><a href="/agro-articles/16-Vyraschivanie-salata.htm"><img width="210" border="0" src="/agro-articles/pictures/16t.jpg"></a> <b><a href="/agro-articles/16-Vyraschivanie-salata.htm">Выращивание салата</a></b></div>  <div class="news_line"></div></div>
<div class="news_position"> <div id="news_text"><a href="/agro-articles/17-Vyraschivanie-petrushki.htm"><img width="210" border="0" src="/agro-articles/pictures/17t.jpg"></a> <b><a href="/agro-articles/17-Vyraschivanie-petrushki.htm">Выращивание петрушки</a></b></div> <div class="news_line"></div></div>
<div class="news_position"> <div id="news_text"><a href="/agro-articles/18-Vyraschivanie-ukropa.htm"><img width="210" border="0" src="/agro-articles/pictures/18t.jpg"></a> <b><a href="/agro-articles/18-Vyraschivanie-ukropa.htm">Выращивание укропа</a></b></div>  <div class="news_line"></div></div>
<div class="news_position"> <div id="news_text"><a href="/agro-articles/19-Vyraschivanie-seldereya.htm"><img width="210" border="0" src="/agro-articles/pictures/19t.jpg"></a> <b><a href="/agro-articles/19-Vyraschivanie-seldereya.htm">Выращивание сельдерея</a></b></div>  </div>
</ul>
